title = 'attentionSpan.equals(null)'
theme = "freelancer"
baseURL = 'http://attentionspan.nl/'
languageCode = 'en-us'
paginate = 9

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      description = 'meaningless&nbsp;mumblings &&nbsp;meandering&nbsp;projects'
  [languages.nl]
    languageName = "Nederlands"
    weight = 2
    [languages.nl.params]
      description = 'meningloos&nbsp;gemompel &&nbsp; dwalende&nbsp;projecten'

[params]
  name = "attentionSpan.nl"
  author = 'Edwin van Nes'
  homePosts = 3
  homeProjects = 3

[[params.social.personal]]
  text = "facebook.com/edwinvannes"
  link = "https://www.facebook.com/edwinvannes/" 
  icon = "facebook-f"

[[params.social.personal]]
  text = "instagram.com/edwin_dus"
  link = "https://www.instagram.com/edwin_dus/" 
  icon = "instagram"

[[params.social.personal]]
  text = "linkedin.com/in/edwinvannes"
  link = "https://www.linkedin.com/in/edwinvannes/" 
  icon = "linkedin"

[[params.social.dacorsa]]
  text = "dacorsa.com"
  link = "https://dacorsa.com" 
  family = "fa-solid"
  icon = "fa-link"

[[params.social.dacorsa]]
  text = "flickr.com/photos/dacorsa"
  link = "https://www.flickr.com/photos/dacorsa/" 
  family = "fa-brands"
  icon = "fa-flickr"

[[params.social.dacorsa]]
  text = "facebook.com/dacorsa.profile"
  link = "https://www.facebook.com/dacorsa.profile/" 
  family = "fa-brands"
  icon = "fa-facebook-f"

[[params.social.dacorsa]]
  text = "instagram.com/dacorsa_com"
  link = "https://www.instagram.com/dacorsa_com/" 
  family = "fa-brands"
  icon = "fa-instagram"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
