baseURL = 'http://attentionspan.nl/'
languageCode = 'en-us'
title = 'attentionSpan.equals(null)'
theme = "freelancer"
paginate = 9

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    weight = 1
  [languages.nl]
    weight = 2
    [languages.nl.params]
      description = 'meningloos&nbsp;gemompel&nbsp;& dwalende&nbsp;projecten'
      aboutLeft = "MTV generatie, trotse vader en partner, ontleder van Prince muziek sinds 1984, liever Star Wars dan Star Trek en verzamelaar van te veel Ferrari boeken en nerdy gadgets"
      aboutRight = "Vakman, ingenieur & knutselaar, revaliderend perfectionist & amateur, steeds meer wantrouwend dat ook niemand anders weet wat ze doen"

[params]
  name = "attentionSpan.nl"
  homePosts = 3
  homeProjects = 3

  author = 'Edwin van Nes'
  description = 'meaningless&nbsp;mumblings &&nbsp;meandering&nbsp;projects'
  aboutLeft = "MTV generation, proud Father and partner, scrutinizing Prince music since 1984, enjoying Star Wars over Star Trek, and collecting too much Ferrari books and nerdy gadgets"
  aboutRight = "Craftsman, engineer & thinkerer, recovering perfectionist & amateur, getting more-and-more suspicious that nobody else knows what they're doing either"

[[params.social.personal]]
  text = "facebook.com/edwinvannes"
  link = "https://www.facebook.com/edwinvannes/" 
  icon = "facebook-f"

[[params.social.personal]]
  text = "instagram.com/edwin_dus"
  link = "https://www.instagram.com/edwin_dus/" 
  icon = "instagram"

[[params.social.personal]]
  text = "linkedin.com/in/edwinvannes"
  link = "https://www.linkedin.com/in/edwinvannes/" 
  icon = "linkedin"

[[params.social.dacorsa]]
  text = "dacorsa.com"
  link = "https://dacorsa.com" 
  family = "fa-solid"
  icon = "fa-link"

[[params.social.dacorsa]]
  text = "flickr.com/photos/dacorsa"
  link = "https://www.flickr.com/photos/dacorsa/" 
  family = "fa-brands"
  icon = "fa-flickr"

[[params.social.dacorsa]]
  text = "facebook.com/dacorsa.profile"
  link = "https://www.facebook.com/dacorsa.profile/" 
  family = "fa-brands"
  icon = "fa-facebook-f"

[[params.social.dacorsa]]
  text = "instagram.com/dacorsa_com"
  link = "https://www.instagram.com/dacorsa_com/" 
  family = "fa-brands"
  icon = "fa-instagram"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
