baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'attentionSpan.equals(null)'
theme = "freelancer"

[params]
  name = "attentionSpan.nl"
  tagLine = "meaningless mumblings & meandering projects"
  homePosts = 3
  homeProjects = 3

  aboutLeft = "Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional SASS stylesheets for easy customization."
  aboutRight = "You can create your own custom avatar for the masthead, change the icon in the dividers, and add your email address to the contact form to make it fully functional!"

[[params.social.personal]]
  text = "facebook.com/edwinvannes"
  link = "https://www.facebook.com/edwinvannes/" 
  icon = "facebook-f"

[[params.social.personal]]
  text = "instagram.com/edwin_dus"
  link = "https://www.instagram.com/edwin_dus/" 
  icon = "instagram"

[[params.social.personal]]
  text = "linkedin.com/in/edwinvannes"
  link = "https://www.linkedin.com/in/edwinvannes/" 
  icon = "linkedin"

[[params.social.dacorsa]]
  text = "dacorsa.com"
  link = "https://dacorsa.com" 
  family = "fa-solid"
  icon = "fa-link"

[[params.social.dacorsa]]
  text = "flickr.com/photos/dacorsa"
  link = "https://www.flickr.com/photos/dacorsa/" 
  family = "fa-brands"
  icon = "fa-flickr"

[[params.social.dacorsa]]
  text = "facebook.com/dacorsa.profile"
  link = "https://www.facebook.com/dacorsa.profile/" 
  family = "fa-brands"
  icon = "fa-facebook-f"

[[params.social.dacorsa]]
  text = "instagram.com/dacorsa_com"
  link = "https://www.instagram.com/dacorsa_com/" 
  family = "fa-brands"
  icon = "fa-instagram"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
